"""items table

Revision ID: 4d9e7420d33a
Revises: b5b9f0bd6845
Create Date: 2022-11-26 00:09:56.147067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9e7420d33a'
down_revision = 'b5b9f0bd6845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_author', sa.String(length=15), nullable=True),
    sa.Column('name_item', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
